[streamdeck]
    brightness = 30

[modules]
    [modules.keylight]
        names = ["Key Light Left", "Key Light Right"]
    [modules.motu]
        ip = "10.0.1.5"
        color = [255, 0, 255]
    #[modules.camera]
    #    name = "A:4BE2529F"
    #[modules.other]
    #    something = "I AM TYPING SOMETHING THIS IS A STRING"


##Defined Actions
[[action]]
    btn = 0
    module = "motu"
    action = "vol_up"
    desc = "VOL +"
    value = "volume"
    display = "volume"

[[action]]
    btn = 5
    module = "motu"
    action = "vol_down"
    desc = "VOL -"
    value = "volume"
    display = "volume"

[[action]]
    btn = 3
    module = "keylight"
    action = "left_light_up"
    desc = "LEFT +"
    value = "left_intensity"
    display = "left_intensity"

[[action]]
    btn = 8
    module = "keylight"
    action = "left_light_down"
    desc = "LEFT -"
    value = "left_intensity"

[[action]]
    btn = 4
    module = "keylight"
    action = "right_light_up"
    desc = "RIGHT +"
    value = "right_intensity"
    display = "right_intensity"

[[action]]
    btn = 9
    module = "keylight"
    action = "right_light_down"
    desc = "RIGHT -"
    value = "right_intensity"

[[action]]
    btn = 14
    module = "keylight"
    action = "toggle_power"
    desc = "TOGGLE"
    value = "power"
    display = "power"
